#!/bin/bash
VERSION=`git tag | tail -1 | sed 's/^v//'`
VDIR=/tmp/kplex-$VERSION
rm -rf $VDIR
mkdir $VDIR
make clean
cp * $VDIR
rm $VDIR/release
echo "/^CFLAGS=/s/^/#/
$
-3,.d
w" | ed -s $VDIR/Makefile >/dev/null
(cd /tmp && tar cf - ${VDIR##*/} | gzip > kplex.${VERSION}.tgz)
