#!/bin/bash
VERSION=`git describe --abbrev=0 | sed 's/^v//'`
VDIR=/tmp/kplex-$VERSION
rm -rf $VDIR
mkdir $VDIR
make clean
echo "#define VERSION \"$VERSION\"" > version.h
cp * $VDIR
rm $VDIR/release $VDIR/base_version
echo "$
-3,.d
w" | ed -s $VDIR/Makefile >/dev/null
(cd /tmp && tar cf - ${VDIR##*/} | gzip > kplex-${VERSION}.tgz)
